data:
  src_suffix: ".src"
  tgt_suffix: ".tgt"
  data_prefix: "../data/letter/data"
  predict_prefix: "../data/letter/predict"
  embed_file: "../resource/letter_embedding_64.txt"
  out_dir: "../experiment/letter/"
  
model:
  encoder_type: 'bi' # uni | bi
  num_units: 128
  num_layers: 4
  dropout: 0.2
  embed_dim: 64
  max_gradient_norm: 5.0
  batch_size: 128
  coverage: True
  max_len: 15

train:
  learning_rate: 0.01
  num_epochs: 1

infer:
  infer_mode: 'greedy' # beam_search
  beam_width: 10
  length_penalty_weight: 1.0